import type { Metadata } from "next"
import Link from "next/link"
import { Separator } from "@/components/ui/separator"
import { ShieldCheck, Mail, Clock, Eye, XCircle } from "lucide-react"
import { FaGithub as Github } from "react-icons/fa6"

export const metadata: Metadata = {
  title: "Security Policy",
  description: "How to responsibly disclose security vulnerabilities on isaacadjei.me.",
  alternates: {
    canonical: "https://www.isaacadjei.me/security-policy",
  },
  openGraph: {
    images: ["/api/og?title=Security%20Policy&description=How%20to%20responsibly%20disclose%20security%20vulnerabilities%20on%20isaacadjei%2Eme%2E"],
  },
}

export default function SecurityPolicyPage() {
  return (
    <div className="container max-w-3xl py-24 space-y-16">
      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <ShieldCheck className="h-8 w-8 text-primary" />
          <h1 className="text-4xl font-bold tracking-tight">Security Policy</h1>
        </div>
        <p className="text-sm text-muted-foreground font-mono">Last updated: October 2026</p>
        <p className="text-lg text-muted-foreground leading-relaxed">
          I take the security of this site seriously. If you have discovered a vulnerability, I
          appreciate you letting me know responsibly.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          This page covers this website. For my software and hardware{" "}
          <Link
            href="/projects"
            className="text-primary underline underline-offset-4 hover:text-primary/80 transition-colors"
          >
            projects
          </Link>
          , each repository&apos;s own security policy applies where it has one and the shared
          general policy lives alongside this page in the repository below.
        </p>
        <p className="text-sm text-muted-foreground">
          <a
            href="https://github.com/zaccesss/security-policy"
            target="_blank"
            rel="noreferrer"
            className="inline-flex items-center gap-1.5 text-primary underline underline-offset-4 hover:text-primary/80 transition-colors"
          >
            <Github className="h-4 w-4" />
            Also on GitHub: zaccesss/security-policy
          </a>
        </p>
      </section>

      <Separator />

      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <Eye className="h-6 w-6 text-primary" />
          <h2 className="text-2xl font-bold">In scope</h2>
        </div>
        <p className="text-muted-foreground leading-relaxed">
          This policy covers <span className="font-medium text-foreground">isaacadjei.me</span> and
          all its subdomains. Examples of issues that are in scope:
        </p>
        <ul className="list-disc list-inside space-y-2 text-muted-foreground">
          <li>Cross-site scripting (XSS)</li>
          <li>Cross-site request forgery (CSRF)</li>
          <li>Authentication or authorisation bypass</li>
          <li>Sensitive data exposure</li>
          <li>Server-side injection vulnerabilities</li>
        </ul>
      </section>

      <Separator />

      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <XCircle className="h-6 w-6 text-primary" />
          <h2 className="text-2xl font-bold">Out of scope</h2>
        </div>
        <p className="text-muted-foreground leading-relaxed">
          The following are explicitly out of scope and should not be reported:
        </p>
        <ul className="list-disc list-inside space-y-2 text-muted-foreground">
          <li>Vulnerabilities in third-party services I do not control (Vercel, Cloudflare, GitHub, Resend, Upstash, Supabase, Sentry, Google and the map tile providers)</li>
          <li>Denial of service attacks or volumetric testing of any kind</li>
          <li>Social engineering or phishing attempts targeting me or visitors</li>
          <li>Issues that require physical access to my devices</li>
          <li>Missing security headers that do not present a practical exploit path</li>
          <li>Reports generated by automated scanners without manual validation</li>
        </ul>
      </section>

      <Separator />

      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <Mail className="h-6 w-6 text-primary" />
          <h2 className="text-2xl font-bold">How to report</h2>
        </div>
        <p className="text-muted-foreground leading-relaxed">
          The preferred route is a{" "}
          <a
            href="https://github.com/zaccesss/isaacadjei.me/security/advisories/new"
            target="_blank"
            rel="noreferrer"
            className="text-primary underline underline-offset-4 hover:text-primary/80 transition-colors"
          >
            private security advisory
          </a>{" "}
          on the site&apos;s public repository. Only you and I can see it, it supports attachments and
          the fix can be tracked against the report.
        </p>
        <p className="text-muted-foreground leading-relaxed">
          You can also send vulnerability reports by email to{" "}
          <a
            href="mailto:contact@isaacadjei.me"
            className="text-primary underline underline-offset-4 hover:text-primary/80 transition-colors"
          >
            contact@isaacadjei.me
          </a>{" "}
          with the subject line{" "}
          <span className="font-mono text-sm bg-muted px-1.5 py-0.5 rounded">Security Disclosure</span>.
          If email is not convenient, you can also use the{" "}
          <Link
            href="/contact"
            className="text-primary underline underline-offset-4 hover:text-primary/80 transition-colors"
          >
            contact page
          </Link>{" "}
          - note that the contact form does not support attachments, so paste any supporting
          material inline.
        </p>
        <p className="text-foreground leading-relaxed font-medium">
          Please include the following in your report:
        </p>
        <ul className="list-disc list-inside space-y-2 text-muted-foreground">
          <li>The affected URL or component</li>
          <li>Your browser, device and operating system (where relevant)</li>
          <li>Step-by-step instructions to reproduce the issue</li>
          <li>What you expected to happen versus what actually happened</li>
          <li>Screenshots, screen recordings or proof-of-concept code if available</li>
        </ul>
        <p className="text-muted-foreground leading-relaxed">
          Please do not publicly disclose the issue until I have had a reasonable opportunity to
          investigate and address it.
        </p>
      </section>

      <Separator />

      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <Clock className="h-6 w-6 text-primary" />
          <h2 className="text-2xl font-bold">Response timeline</h2>
        </div>
        <div className="space-y-2 text-muted-foreground">
          <p>I aim to respond to all reports within the following timeframes:</p>
          <ul className="list-disc list-inside space-y-2">
            <li>Initial acknowledgement within <span className="font-medium text-foreground">3 business days</span></li>
            <li>Assessment and triage within <span className="font-medium text-foreground">7 business days</span></li>
            <li>Resolution or mitigation plan within <span className="font-medium text-foreground">30 days</span> for valid issues</li>
          </ul>
        </div>
      </section>

      <Separator />

      <section className="space-y-4">
        <h2 className="text-2xl font-bold">Good faith</h2>
        <p className="text-muted-foreground leading-relaxed">
          I will not take legal action against researchers who act in good faith, follow this policy
          and do not access, modify or delete data beyond what is needed to demonstrate the
          vulnerability. Valid reporters will be acknowledged on the{" "}
          <a href="/hall-of-fame" className="text-primary underline underline-offset-4 hover:text-primary/80 transition-colors">
            Hall of Fame
          </a>
          .
        </p>
      </section>
    </div>
  )
}
